openapi: 3.0.0
info:
    title: Template
    version: '1.0'
servers:
    - url: 'http://localhost:3000'
paths:
    /:
        get:
            summary: Home
            operationId: get-home
            responses:
                '200':
                    description: OK
    /login:
        post:
            summary: Login
            operationId: post-auth
            responses:
                '200':
                    description: OK
                '400':
                    description: Bad Request
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
                            required:
                                - email
                                - password
        parameters: []
    /users/me:
        get:
            summary: Get current user
            tags: []
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
            operationId: get-users-me
            description: ''
    /schools:
        get:
            summary: Your GET endpoint
            tags: []
            responses:
                '200':
                    description: OK
            operationId: get-schools
        parameters: []
        post:
            summary: ''
            operationId: post-schools
            responses:
                '200':
                    description: OK
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            description: ''
                            additionalProperties: false
                            properties:
                                name:
                                    type: string
                                url:
                                    type: string
                                    format: uri
                                address:
                                    type: string
                                city:
                                    type: string
                                postal:
                                    type: number
                                description:
                                    type: string
                            required:
                                - name
                                - url
                                - address
                                - city
                                - postal
                                - description
                description: ''
    '/schools/{id}':
        parameters:
            - schema:
                  type: string
              name: id
              in: path
              required: true
        get:
            summary: Your GET endpoint
            tags: []
            responses:
                '200':
                    description: OK
            operationId: get-schools-id
            parameters: []
            description: Gets school by given id.
        patch:
            summary: ''
            operationId: patch-schools-id
            responses:
                '200':
                    description: OK
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            description: ''
                            additionalProperties: false
                            properties:
                                name:
                                    type: string
                                url:
                                    type: string
                                    format: uri
                                address:
                                    type: string
                                city:
                                    type: string
                                postal:
                                    type: number
                                description:
                                    type: string
                description: ''
            description: Updates school.
        delete:
            summary: ''
            operationId: delete-schools-id
            responses:
                '200':
                    description: OK
            description: Deletes school.
    /articles:
        get:
            summary: Your GET endpoint
            tags: []
            responses:
                '200':
                    description: OK
            operationId: get-articles
        post:
            summary: ''
            operationId: post-articles
            responses:
                '200':
                    description: OK
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            additionalProperties: false
                            properties:
                                name:
                                    type: string
                                url:
                                    type: string
                                content:
                                    type: string
            parameters: []
    '/articles/{id}':
        parameters:
            - schema:
                  type: string
              name: id
              in: path
              required: true
        get:
            summary: Your GET endpoint
            tags: []
            responses:
                '200':
                    description: OK
            operationId: get-articles-id
        patch:
            summary: ''
            operationId: patch-articles-id
            responses:
                '200':
                    description: OK
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            description: ''
                            additionalProperties: false
                            properties:
                                name:
                                    type: string
                                url:
                                    type: string
                                content:
                                    type: string
        delete:
            summary: ''
            operationId: delete-articles-id
            responses:
                '200':
                    description: OK
    /inviteUser:
        post:
            summary: ''
            operationId: post-inviteUser
            responses:
                '200':
                    description: OK
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            additionalProperties: false
                            properties:
                                email:
                                    type: string
                                    format: email
                            required:
                                - email
    /registration:
        post:
            summary: ''
            operationId: post-register
            responses:
                '200':
                    description: OK
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            additionalProperties: false
                            properties:
                                token:
                                    type: string
                                name:
                                    type: string
                                email:
                                    type: string
                                    format: email
                                password:
                                    type: string
                            required:
                                - token
                                - name
                                - email
                                - password
        parameters: []
components:
    schemas:
        User:
            title: User
            type: object
            properties:
                id:
                    type: string
                email:
                    type: string
            required:
                - id
                - email
    securitySchemes: {}
